Server:
  RunMode: debug
  HttpPort: 8088
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: ./logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: ~
  Host: ~
  DBName: go-service
  TablePrefix: ''
  Charset: utf8
  ParseTime: "true"
  MaxIdleConns: 10
  MaxOpenConns: 30
  MaxLifeTime: 10
Redis:
  Host: ~
  Password: ~
  DbIndex: 0
  IsAuth: True