Server:
  RunMode: debug
  HttpPort: 8091
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: ./logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: 123456
  Host: 192.168.1.5:3306
  DBName: go-service
  TablePrefix: ''
  Charset: utf8
  ParseTime: "true"
  MaxIdleConns: 10
  MaxOpenConns: 30
  MaxLifeTime: 10
Redis:
  Host: 192.168.1.5:6379
  Password: 123456
  DbIndex: 0
  IsAuth: True